== DEMO

Preparation :
. clone mes dockerfiles sour github
. tirer les images ubuntu
. construire les images java8 et maven

=== BASH DANS UN CONTENEUR

. lancer un bash dans un conteneur : `sudo docker run --rm -it ubuntu:14.10 bash`
.. je suis bien dans une ubuntu : `cat /etc/os-release`
.. est-ce vraiment une ubuntu ? `uname -a`

. un conteneur est isolé du monde : 
.. `rm -rf /bin`
.. pas grave, je peux en redémarrer un *tout propre* : `sudo docker run --rm -it ubuntu:14.10 bash`
.. essayez de faire ça avec un VM, vous avez interêt à avoir un snaphost récent...

=== HELLO WORLD

. hello world ?
.. `sudo docker run --rm -it ubuntu:14.10 echo "Hello world!"`

. comment on construit des images docker ? -> via un Dockerfile (autres possibilités)
.. hello world dans mon image à moi, via un docker file ? cf dossier hello
.. on construit l'image avec `sudo docker build -t nocquidant/hello .`
.. a noter l'utilisation d'un cache (on en reparlera plus loin)
.. on lance l'image avec `drr nocquidant/hello`

=== COWSAY ET FORTUNE

. entre le FROM et la CMD, je peux faire des choses... et notamment installer une application
.. cowsay et fortune !!
.. on construit l'image, la 1ere fois c'est long
.. il existe un cache, si la séquence d'opérations existe déjà et dans le même ordre, il redemarre à la dernière commande
.. on execute (je n'ai pas installer cowsay sur ma machine), ca marche !

. NOTE : le cache de docker
.. fonctionnalité gagnante
.. forte productivité !!
.. difficile de revenir en arrière quand vous construisez une VM (les gens ont inventé Vagrant)

=== FICHIER QUI PROVIENT DE MA MACHINE

. comment créer un conteneur avec des fichiers qui proviennent de ma machine ?
.. cowsay avec mon fichier
.. possibilité de générer un tar.gz de mon image et de la donner à quelqu'un 
.. -> le même binaire s'executera avec le même contexte !

=== EXECUTER MON PROJET JAVA SUR GITHUB

==== GIT

. notion de volume pour binder un repertoire de ma machine avec un repertoire du conteneur
.. exemple de git clone dans le repertoire courant
.. sans avoir git je clone 1 projet git sur ma machine
.. ca marche aussi avec les fichiers (un fichier de config peut être remplacé par un autre)

==== JAVA

. dockerfile et projet Java
.. soit vous indiquez dans un Readme.txt les operations a effectuer pour construire le projet (version de mvn)
.. soit vous ajoutez un dockerfile à votre projet pour le construire (pas besoin d'installer mvn, des libs natives...)
... + reproductible
... + dependances figées

== ALIAS

alias db='sudo docker build'
alias dr='sudo docker run'
alias drr='sudo docker run --rm'
alias drmall='sudo docker rm -v $(sudo docker ps -a -q)'
alias drmiall='sudo docker rmi -f $(sudo docker images -q)'

alias dgit='drr -v /home/nicolas/Dropbox/Temp/demo/3_git/my-spring-boot-sample:/src -t nocquidant/git'
